### PR TITLE
create basic yazi indicator for zsh robbyrussel

### PR DESCRIPTION
**Pull request by arcstur**
I really liked this plugin. I modified the posix one to look good into my zsh with the oh my zsh's robbyrussel theme. What do you think about it?

Here's a screenshot:

image

Here's without it:

image

### CODE REVIEW

**Comment by arcstur** [comment]
If you think it's good, I can modify the README to insert this one there.

**Comment by Sonico98** [comment]
The code seems to be almost the same to that of the default zsh / bash prompt. Don't you think it would be a better idea instead to explain in the README how to add color to the yazi indicator for such simple prompts? It would require a bit of manual intervention from users (unless we script it!) but that way all similar prompt themes could benefit from it.

**Comment by arcstur** [comment]
Yeah, maybe that would be best!! I wonder, that color configuration is from zsh itself?

**Comment by Sonico98** [comment]
Yes, `autoload -U colors && colors` has to be executed at the top of `yazi.sh` and then you can assign the colors like you did for robbyrussel: `%{$fg[color]%}` and  `%{$reset_color%}`

**Pull request closed without merging**
